### ISSUE TITLE
Druppel seems broken

### ISSUE THREAD

**Issue by jerome2710** [peperzaken/jeeves#4]
While running Jeeves for the first time, I noticed the weather-slide shows a blank black page. Terminal returns the following error:

`error: Error while getting precipitation results:TypeError: Cannot call method 'split' of undefined`

Any ideas how I could fix this?
I did not change any files or added my own location values yet.

**Comment by RubenHoms** [comment]
Thanks for reporting this issue @jerome2710 !

Though I can't reproduce this myself, I have a clean version of Jeeves up-and-running and there seems to be no errors on the druppel slide. I have noticed some lag lately coming from the API we're using to create this slide, it might be that a request timed out and this is the end result of that.

I assume it's happening either [here](https://github.com/peperzaken/jeeves/blob/master/server/slides/druppel/sources.js#L25) or [here](https://github.com/peperzaken/jeeves/blob/master/server/slides/druppel/sources.js#L34). A simple check to see if the response body is empty should clear that error up.

Could you try again to see if it was a temporary hiccup rather than a persistent bug?

**Comment by jerome2710** [comment]
Hi Ruben,

Thanks for your reply!
It seems that Druppel corrected this issue themselves, the page is working again now.

I will notify you when the problem re-occurs.
